name: Code Coverage

on:
  push:
    branches: ["master"]
  pull_request:
    branches: ["master"]
  workflow_dispatch:

jobs:
  coverage:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install dependencies
        run: make deps

      - name: Build
        run: make build

      - name: Run tests
        run: ./main

      - name: Create coverage folder
        run: mkdir -p ${{ github.workspace }}/coverage

      - name: Generate Gcovr XML report
        run: gcovr --cobertura -o coverage-gcovr.xml

      # - name: Cobertura Action
      #   uses: 5monkeys/cobertura-action@master
      #   if: success() || failure()
      #   with:
      #     path: ${{ github.workspace }}/coverage/coverage-gcovr.xml
      #     minimum_coverage: 35
      #     repo_token: ${{ secrets.COBERTURA_TOKEN }}

      # - name: Code Coverage Summary Report
      #   uses: irongut/CodeCoverageSummary@v1.3.0
      #   with:
      #     filename: coverage-gcovr.xml
      #     badge: true
      #     fail_below_min: true
      #     format: markdown
      #     hide_branch_rate: false
      #     hide_complexity: true
      #     indicators: true
      #     output: both
      #     thresholds: "50 80"

      # - name: Add Coverage PR Comment
      #   uses: marocchino/sticky-pull-request-comment@v2
      #   if: github.event_name == 'pull_request'
      #   with:
      #     recreate: true
      #     path: code-coverage-results.md

      - name: Publish Test Report
        uses: mikepenz/action-junit-report@v4
        if: success() || failure() # always run even if the previous step fails
        with:
          report_paths: coverage-gcovr.xml
