name: Build

on:
  push:
    branches: ["master"]
  pull_request:
    branches: ["master"]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: cpp-linter/cpp-linter-action@v2
        with:
          style: "LLVM"
          tidy-checks: "-*" # disable tidy check
          lines-changed-only: "false"

      - name: Install dependency
        run: make deps

      - name: 1. Compile
        run: make build
      - name: 2. Run executable
        run: ./main
      - name: 3. Generate Gcovr XML report
        run: gcovr --xml -o coverage/coverage-gcovr.xml

      # - name: Publish coverage reports
      #   uses: actions/upload-artifact@v2
      #   with:
      #     name: coverage-reports
      #     path: |
      #       coverage-cobertura.xml
      #       coverage-gcovr.xml

      # - name: Code Coverage Summary Report
      #   uses: irongut/CodeCoverageSummary@v1.3.0
      #   with:
      #     filename: coverage.cobertura.xml
