name: Build

on:
  push:
    branches: ["master"]
  pull_request:
    branches: ["master"]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: cpp-linter/cpp-linter-action@v2
        with:
          style: "LLVM"
          tidy-checks: "-*" # disable tidy check
          lines-changed-only: "false"

      - name: Install dependency
        run: make deps

      - name: 1. Compile
        run: make build
      - name: 2. Run executable
        run: ./main
      - name: 3. Generate reports
        run: |
          make lcov-report
          lcov_cobertura --base-dir . --output coverage-cobertura.xml --rc lcov_branch_coverage=1 lcov.info
          gcovr --xml -o coverage-gcovr.xml

      - name: Publish coverage reports
        uses: actions/upload-artifact@v2
        with:
          name: coverage-reports
          path: |
            coverage-cobertura.xml
            coverage-gcovr.xml

    # - name: Upload lcov and gcovr reports
    #   if: github.ref == 'refs/heads/master'
    #   run: |
    #     git config user.name github-actions
    #     git config user.email github-actions@github.com
    #     git checkout -b coverage
    #     git add --all
    #     git commit -m "Upload lcov and gcovr reports"
    #     git push -f origin coverage
