name: Code Coverage

on:
  push:
    branches: ["master"]
  pull_request:
    branches: ["master"]
  workflow_dispatch:

permissions:
  checks: write

jobs:
  coverage:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install dependencies
        run: make deps

      - name: Build
        run: make build

      - name: Run tests
        run: ./main

      - name: Create coverage folder
        run: mkdir -p ${{ github.workspace }}/coverage

      - name: Generate Gcovr XML report
        run: gcovr --cobertura -o coverage-gcovr.xml

      - name: Generate sumary report
        uses: ./.github/actions/coverage-gate
        with:
          filename: coverage-gcovr.xml
          thresholds: "50 80"
